#!/bin/bash

# Clean script for Bun preload library
# Removes generated library files

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PRELOAD_DIR="$PROJECT_DIR/asherah-bun-preload"
LIB_DIR="$PRELOAD_DIR/lib"

echo "Cleaning Bun preload library artifacts..."

cd "$LIB_DIR"

# Remove generated library files for all platforms
rm -f bun_warmup_minimal.dylib  # macOS
rm -f bun_warmup_minimal.so     # Linux
rm -f bun_warmup_minimal.dll    # Windows
rm -f bun_warmup_minimal.h      # Header file (generated by Go)

echo "✅ Bun preload library artifacts cleaned"