name: Publish Asherah-Node

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  publish-package:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: node:bullseye
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm install
    - name: Download Asherah-Cobhan
      run: scripts/download-libasherah.sh
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Verify tag matches package version
      run: scripts/set-version.sh ${GITHUB_REF#refs/*/}
    - name: Publish (main)
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && npm publish; rm .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
